FROM apache/airflow:2.7.2

# upgrade pip to latest version
RUN pip install -U pip --upgrade pip

# Working directory
WORKDIR /app

# Copy requirements.txt file to workdir
COPY requirements.txt .

# install python packages
RUN pip install --no-cache-dir -r requirements.txt